[package]
name = "fluff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html5ever = "0.26.0"
markup5ever_rcdom = "0.2.0"
ureq = "2.6.1"
